name: Deploy to GitHub Pages

on:
  push:
    branches:
      - bot-list-angular # Trigger su push al branch principale di sviluppo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Installa dipendenze
      - name: Install dependencies
        run: npm install

      # 4. Compila il progetto con configurazione production
      - name: Build project
        run: npm run build -- --output-path=dist/bot-list-app --configuration=production

      # 5. Deploy sulla branch bot-list
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/bot-list-app
          publish_branch: bot-list
