name: my_app
description: Un'app Flutter di esempio
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0+3
  path_provider: ^2.0.11

flutter:
  uses-material-design: true