name: scriptagher
description: flutter scriptagher app
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter

  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  logging: ^1.3.0
  intl: ^0.20.2
  shelf: ^1.4.2
  archive: ^4.0.7
  shelf_router: ^1.1.3
  http: ^1.2.2
  path_provider: ^2.1.3
  bitsdojo_window: ^0.1.6
  carousel_slider: ^5.0.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true