name: Deploy to GitHub Pages

on:
  push:
    branches:
      - bot-list

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout il codice
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Installa le dipendenze
      - name: Install dependencies
        run: npm install

      # 4. Compila il progetto
      - name: Build project
        run: npm run build -- --output-path=dist --configuration=production

      # 5. Fai il deploy su gh-pages
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages