name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter test
        run: flutter test --dart-define=USE_DESKTOP_FRAME=false

  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Ensure Android platform sources
        run: flutter create . --platforms=android -t app

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Android APK (debug)
        run: flutter build apk --debug

      - name: Build Flutter web bundle
        run: flutter build web

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload Flutter web bundle
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web
