name: Preview Deploy

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.preview-vars.outputs.pr_number }}
      preview_path: ${{ steps.preview-vars.outputs.preview_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Capture preview metadata
        id: preview-vars
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "pr_number=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
            echo "preview_path=previews/pr-${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          else
            echo "pr_number=" >> "$GITHUB_OUTPUT"
            echo "preview_path=" >> "$GITHUB_OUTPUT"
          fi

      - name: Build project
        run: |
          rm -rf dist
          if [ -n "${{ steps.preview-vars.outputs.pr_number }}" ]; then
            PR_NUMBER="${{ steps.preview-vars.outputs.pr_number }}"
            PREVIEW_PATH="${{ steps.preview-vars.outputs.preview_path }}"
            npm run build -- --base-href "/scriptagher/${PREVIEW_PATH}/" --output-path "dist/${PREVIEW_PATH}"
          else
            npm run build
          fi

      - name: Upload preview artifact
        if: ${{ steps.preview-vars.outputs.pr_number != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: preview-dist
          path: dist/${{ steps.preview-vars.outputs.preview_path }}
          if-no-files-found: error

  deploy-preview:
    if: ${{ needs.build.outputs.pr_number != '' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Download preview artifact
        uses: actions/download-artifact@v4
        with:
          name: preview-dist
          path: preview-artifact

      - name: Prepare preview content
        env:
          PREVIEW_PATH: ${{ needs.build.outputs.preview_path }}
        run: |
          mkdir -p "$(dirname "${PREVIEW_PATH}")"
          rm -rf "${PREVIEW_PATH}"
          rsync -a --delete "preview-artifact/dist/${PREVIEW_PATH}/" "${PREVIEW_PATH}/"

      - name: Commit preview update
        env:
          PR_NUMBER: ${{ needs.build.outputs.pr_number }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git status --short "${{ needs.build.outputs.preview_path }}" | grep .; then
            git add "${{ needs.build.outputs.preview_path }}"
            git commit -m "chore: update preview for PR #${PR_NUMBER}"
          else
            echo "No changes to commit"
          fi

      - name: Push preview changes
        run: git push origin gh-pages

      - name: Publish preview link
        env:
          PREVIEW_PATH: ${{ needs.build.outputs.preview_path }}
          PR_NUMBER: ${{ needs.build.outputs.pr_number }}
        run: |
          BASE_URL="https://$GITHUB_REPOSITORY_OWNER.github.io/${GITHUB_REPOSITORY##*/}"
          PREVIEW_URL="${BASE_URL}/${PREVIEW_PATH}/"
          {
            echo "### Preview ready"
            echo
            echo "* **PR**: #${PR_NUMBER}"
            echo "* **URL**: ${PREVIEW_URL}"
          } >> "$GITHUB_STEP_SUMMARY"
